version: '3.8'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=heroes
      - MYSQL_PASSWORD=dccomics
      - MYSQL_DATABASE=heroes
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
